# Generated by Django 4.2.19 on 2025-03-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Open', models.IntegerField()),
                ('High', models.IntegerField()),
                ('Low', models.IntegerField()),
                ('Close', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Open', models.IntegerField()),
                ('High', models.IntegerField()),
                ('Low', models.IntegerField()),
                ('Close', models.IntegerField()),
            ],
        ),
    ]
